# Generated by Django 2.2.24 on 2021-08-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customtext_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.BigIntegerField()),
                ('last_name', models.BigIntegerField()),
                ('street_address', models.BigIntegerField()),
                ('city', models.BigIntegerField()),
                ('state', models.BigIntegerField()),
                ('zip_code', models.BigIntegerField()),
                ('activity_preferences', models.BigIntegerField()),
            ],
        ),
    ]
